services:
  baikal:
    image: ghcr.io/aalmenar/baikal:0.12.1
    volumes:
      - ${APP_DATA_DIR}/config:/var/www/baikal/config
      - ${APP_DATA_DIR}/specific:/var/www/baikal/Specific
    x-runtipi:
      internal_port: 80
      is_main: true
x-runtipi:
  schema_version: 2
