services:
  archivebox:
    image: 'archivebox/archivebox:0.7.3'
    command: 'server --quick-init 0.0.0.0:8015'
    volumes:
      - '${APP_DATA_DIR}/data:/data'
    environment:
      - 'PORT=8015'
      - 'PUBLIC_INDEX=${ARCHIVEBOX_PUBLIC_INDEX-true}'
      - 'PUBLIC_SNAPSHOTS=${ARCHIVEBOX_PUBLIC_SNAPSHOTS-true}'
      - 'PUBLIC_ADD_VIEW=${ARCHIVEBOX_PUBLIC_ADD_VIEW-false}'
      - 'ADMIN_USERNAME=${ARCHIVEBOX_USERNAME}'
      - 'ADMIN_PASSWORD=${ARCHIVEBOX_PASSWORD}'
      - 'PUID=1000'
      - 'PGID=1000'
      - 'SEARCH_BACKEND_ENGINE=${ARCHIVEBOX_SEARCH_BACKEND_ENGINE}'
      - 'SEARCH_BACKEND_HOST_NAME=${ARCHIVEBOX_SEARCH_BACKEND_HOST_NAME}'
      - 'SEARCH_BACKEND_PASSWORD=${ARCHIVEBOX_SEARCH_BACKEND_PASSWORD}'
      - 'MEDIA_MAX_SIZE=${ARCHIVEBOX_MEDIA_MAX_SIZE-750m}'
      - 'TIMEOUT=${ARCHIVEBOX_TIMEOUT-60}'
      - 'CHECK_SSL_VALIDITY=${ARCHIVEBOX_CHECK_SSL_VALIDITY-true}'
      - 'SAVE_ARCHIVE_DOT_ORG=${ARCHIVEBOX_SAVE_ARCHIVE_DOT_ORGE-true}'
    x-runtipi:
      internal_port: 8015
      is_main: true
x-runtipi:
  schema_version: 2
