services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.6.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data:/config
      - ${ROOT_FOLDER_HOST}/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    x-runtipi:
      internal_port: 6767
      is_main: true
x-runtipi:
  schema_version: 2
