services:
  authentik-1:
    image: 'ghcr.io/goauthentik/server:2026.2.2'
    command: 'server'
    ports:
      - '9443:9443/tcp'
    volumes:
      - '${APP_DATA_DIR}/data/authentik-media:/media'
      - '${APP_DATA_DIR}/data/authentik-custom-templates:/templates'
    environment:
      - 'AUTHENTIK_POSTGRESQL__HOST=authentik-db'
      - 'AUTHENTIK_POSTGRESQL__USER=authentik'
      - 'AUTHENTIK_POSTGRESQL__NAME=authentik'
      - 'AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}'
      - 'AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}'
    depends_on:
      - 'authentik-db'
    x-runtipi:
      internal_port: 9000
      is_main: true
  authentik-worker:
    image: 'ghcr.io/goauthentik/server:2026.2.2'
    command: 'worker'
    user: 'root'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${APP_DATA_DIR}/data/authentik-media:/media'
      - '${APP_DATA_DIR}/data/authentik-certs:/certs'
      - '${APP_DATA_DIR}/data/authentik-custom-templates:/templates'
    environment:
      - 'AUTHENTIK_POSTGRESQL__HOST=authentik-db'
      - 'AUTHENTIK_POSTGRESQL__USER=authentik'
      - 'AUTHENTIK_POSTGRESQL__NAME=authentik'
      - 'AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}'
      - 'AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}'
    depends_on:
      - 'authentik-db'
  authentik-db:
    image: 'postgres:18-alpine'
    volumes:
      - '${APP_DATA_DIR}/data/postgres:/var/lib/postgresql'
    environment:
      - 'POSTGRES_PASSWORD=${AUTHENTIK_DB_PASSWORD}'
      - 'POSTGRES_USER=authentik'
      - 'POSTGRES_DB=authentik'
    healthcheck:
      test: 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}'
      interval: '30s'
      timeout: '5s'
      retries: 5
      start_period: '20s'
x-runtipi:
  schema_version: 2
