services:
  adguardhome-sync:
    image: 'ghcr.io/bakito/adguardhome-sync:v0.9.0'
    command: 'run --config /config/adguardhome-sync.yaml'
    volumes:
      - '${APP_DATA_DIR}/data/adguardhome-sync.yaml:/config/adguardhome-sync.yaml'
    x-runtipi:
      internal_port: 8080
      is_main: true
x-runtipi:
  schema_version: 2
